[package]
name = "verder-helpen-proto"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
rocket.workspace = true
serde = { workspace = true, features = ["derive"] }
